[package]
name = "hh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.5"
macroquad-platformer = "0.2.0"
macroquad-tiled = "0.2.1"
futures = "0.3.30"
pub-fields = "0.1.1"
